// GENERATED FILE -- do not edit by hand.
// Source: config/sources.yaml via worker/scripts/gen_sources.py
// Regenerate: python worker/scripts/gen_sources.py

import type { SourceDef } from "./sources.js";

// yaml_total=372 worker_supported=288 python_only=84 hourly=18

export const GENERATED_SOURCES: SourceDef[] = [
  {"kind": "linkedin", "name": "linkedin_geo_recent", "cadence": "6h", "url": "https://www.linkedin.com/jobs/", "queries": ["backend", "fullstack", "software"], "locations": ["Remote"], "tprSeconds": 43200},
  {"kind": "indeed", "name": "indeed-egypt-tech", "cadence": "6h", "url": "https://eg.indeed.com/", "queries": ["backend", "fullstack", "software"], "locations": ["Cairo, Egypt", "Egypt"], "country": "Egypt"},
  {"kind": "freehire", "name": "freehire-remote-tech", "cadence": "6h", "url": "https://freehire.me/api/v1/agent/jobs/search", "queries": ["backend", "fullstack", "software"], "locations": ["Remote"]},
  {"kind": "bdjobs", "name": "bdjobs-bangladesh-tech", "cadence": "6h", "url": "https://api.bdjobs.com/Jobs/api/JobSearch/GetJobSearch", "queries": ["backend", "fullstack", "software"], "locations": ["Dhaka, Bangladesh", "Bangladesh"]},
  {"kind": "greenhouse", "name": "stripe", "cadence": "6h", "org": "stripe"},
  {"kind": "greenhouse", "name": "figma", "cadence": "6h", "org": "figma"},
  {"kind": "greenhouse", "name": "datadog", "cadence": "6h", "org": "datadog"},
  {"kind": "greenhouse", "name": "airbnb", "cadence": "6h", "org": "airbnb"},
  {"kind": "greenhouse", "name": "cloudflare", "cadence": "6h", "org": "cloudflare"},
  {"kind": "greenhouse", "name": "github", "cadence": "6h", "org": "github"},
  {"kind": "greenhouse", "name": "gitlab", "cadence": "6h", "org": "gitlab"},
  {"kind": "greenhouse", "name": "pinterest", "cadence": "6h", "org": "pinterest"},
  {"kind": "greenhouse", "name": "doordash", "cadence": "6h", "org": "doordash"},
  {"kind": "greenhouse", "name": "reddit", "cadence": "6h", "org": "reddit"},
  {"kind": "greenhouse", "name": "dropbox", "cadence": "6h", "org": "dropbox"},
  {"kind": "greenhouse", "name": "box", "cadence": "6h", "org": "boxinc"},
  {"kind": "greenhouse", "name": "twist", "cadence": "6h", "org": "twist"},
  {"kind": "greenhouse", "name": "hashicorp", "cadence": "6h", "org": "hashicorp"},
  {"kind": "greenhouse", "name": "mongodb", "cadence": "6h", "org": "mongodb"},
  {"kind": "greenhouse", "name": "elastic", "cadence": "6h", "org": "elastic"},
  {"kind": "greenhouse", "name": "confluent", "cadence": "6h", "org": "confluent"},
  {"kind": "greenhouse", "name": "cockroachlabs", "cadence": "6h", "org": "cockroachlabs"},
  {"kind": "greenhouse", "name": "instacart", "cadence": "6h", "org": "instacart"},
  {"kind": "greenhouse", "name": "lyft", "cadence": "6h", "org": "lyft"},
  {"kind": "greenhouse", "name": "affirm", "cadence": "6h", "org": "affirm"},
  {"kind": "greenhouse", "name": "robinhood", "cadence": "6h", "org": "robinhood"},
  {"kind": "greenhouse", "name": "coinbase", "cadence": "hourly", "org": "coinbase"},
  {"kind": "greenhouse", "name": "gusto", "cadence": "6h", "org": "gusto"},
  {"kind": "greenhouse", "name": "plaid", "cadence": "6h", "org": "plaid"},
  {"kind": "greenhouse", "name": "chime", "cadence": "6h", "org": "chime"},
  {"kind": "greenhouse", "name": "sofi", "cadence": "6h", "org": "sofi"},
  {"kind": "greenhouse", "name": "brex", "cadence": "6h", "org": "brex"},
  {"kind": "greenhouse", "name": "ramp", "cadence": "6h", "org": "ramp"},
  {"kind": "greenhouse", "name": "carta", "cadence": "6h", "org": "carta"},
  {"kind": "greenhouse", "name": "checkr", "cadence": "6h", "org": "checkr"},
  {"kind": "greenhouse", "name": "benchling", "cadence": "6h", "org": "benchling"},
  {"kind": "greenhouse", "name": "samsara", "cadence": "6h", "org": "samsara"},
  {"kind": "greenhouse", "name": "scaleai", "cadence": "6h", "org": "scaleai"},
  {"kind": "greenhouse", "name": "verkada", "cadence": "6h", "org": "verkada"},
  {"kind": "greenhouse", "name": "anduril", "cadence": "6h", "org": "andurilindustries"},
  {"kind": "greenhouse", "name": "palantir", "cadence": "6h", "org": "palantirtechnologies"},
  {"kind": "greenhouse", "name": "openai", "cadence": "6h", "org": "openai"},
  {"kind": "greenhouse", "name": "anthropic", "cadence": "6h", "org": "anthropic"},
  {"kind": "greenhouse", "name": "cohere", "cadence": "6h", "org": "cohere"},
  {"kind": "greenhouse", "name": "cursor", "cadence": "6h", "org": "anysphere"},
  {"kind": "greenhouse", "name": "perplexity", "cadence": "6h", "org": "perplexityai"},
  {"kind": "greenhouse", "name": "glean", "cadence": "6h", "org": "gleanwork"},
  {"kind": "greenhouse", "name": "characterai", "cadence": "6h", "org": "characterai"},
  {"kind": "greenhouse", "name": "mistral", "cadence": "6h", "org": "mistralai"},
  {"kind": "greenhouse", "name": "togetherai", "cadence": "6h", "org": "togetherai"},
  {"kind": "greenhouse", "name": "adept", "cadence": "6h", "org": "adeptai"},
  {"kind": "greenhouse", "name": "jasper", "cadence": "6h", "org": "jasper"},
  {"kind": "greenhouse", "name": "runway", "cadence": "6h", "org": "runway"},
  {"kind": "greenhouse", "name": "replit", "cadence": "6h", "org": "replit"},
  {"kind": "greenhouse", "name": "modal", "cadence": "6h", "org": "modal"},
  {"kind": "greenhouse", "name": "modal-labs", "cadence": "6h", "org": "modallabs"},
  {"kind": "greenhouse", "name": "weights-and-biases", "cadence": "6h", "org": "wandb"},
  {"kind": "greenhouse", "name": "anyscale", "cadence": "6h", "org": "anyscale"},
  {"kind": "greenhouse", "name": "octoai", "cadence": "6h", "org": "octoml"},
  {"kind": "greenhouse", "name": "huggingface", "cadence": "6h", "org": "huggingface"},
  {"kind": "greenhouse", "name": "pinecone", "cadence": "6h", "org": "pinecone"},
  {"kind": "greenhouse", "name": "weaviate", "cadence": "6h", "org": "weaviate"},
  {"kind": "greenhouse", "name": "qdrant", "cadence": "6h", "org": "qdrant"},
  {"kind": "greenhouse", "name": "chroma", "cadence": "6h", "org": "chroma"},
  {"kind": "greenhouse", "name": "sentry", "cadence": "6h", "org": "sentry"},
  {"kind": "greenhouse", "name": "launchdarkly", "cadence": "6h", "org": "launchdarkly"},
  {"kind": "greenhouse", "name": "postman", "cadence": "6h", "org": "postman"},
  {"kind": "greenhouse", "name": "pagerduty", "cadence": "6h", "org": "pagerduty"},
  {"kind": "greenhouse", "name": "circleci", "cadence": "6h", "org": "circleci"},
  {"kind": "greenhouse", "name": "dbt-labs", "cadence": "6h", "org": "dbtlabs"},
  {"kind": "greenhouse", "name": "fivetran", "cadence": "6h", "org": "fivetran"},
  {"kind": "greenhouse", "name": "starburst", "cadence": "6h", "org": "starburstdata"},
  {"kind": "greenhouse", "name": "airbyte", "cadence": "6h", "org": "airbyte"},
  {"kind": "greenhouse", "name": "clickhouse", "cadence": "6h", "org": "clickhouse"},
  {"kind": "greenhouse", "name": "timescale", "cadence": "6h", "org": "timescale"},
  {"kind": "greenhouse", "name": "planetscale", "cadence": "6h", "org": "planetscale"},
  {"kind": "greenhouse", "name": "neon", "cadence": "6h", "org": "neon"},
  {"kind": "greenhouse", "name": "fauna", "cadence": "6h", "org": "fauna"},
  {"kind": "greenhouse", "name": "temporal", "cadence": "6h", "org": "temporal"},
  {"kind": "greenhouse", "name": "prefect", "cadence": "6h", "org": "prefect"},
  {"kind": "greenhouse", "name": "astronomer", "cadence": "6h", "org": "astronomer"},
  {"kind": "greenhouse", "name": "dagster", "cadence": "6h", "org": "elementl"},
  {"kind": "greenhouse", "name": "flyio", "cadence": "6h", "org": "flyio"},
  {"kind": "greenhouse", "name": "render", "cadence": "6h", "org": "render"},
  {"kind": "greenhouse", "name": "railway", "cadence": "6h", "org": "railway"},
  {"kind": "greenhouse", "name": "deno", "cadence": "6h", "org": "deno"},
  {"kind": "greenhouse", "name": "bun", "cadence": "6h", "org": "oven"},
  {"kind": "greenhouse", "name": "datadrivers", "cadence": "6h", "org": "datadrivers"},
  {"kind": "greenhouse", "name": "datadog-eu", "cadence": "6h", "org": "datadog"},
  {"kind": "greenhouse", "name": "sumologic", "cadence": "6h", "org": "sumologic"},
  {"kind": "greenhouse", "name": "dynatrace", "cadence": "6h", "org": "dynatrace"},
  {"kind": "greenhouse", "name": "newrelic", "cadence": "6h", "org": "newrelic"},
  {"kind": "greenhouse", "name": "appdynamics", "cadence": "6h", "org": "appdynamics"},
  {"kind": "greenhouse", "name": "cribl", "cadence": "6h", "org": "cribl"},
  {"kind": "greenhouse", "name": "chronosphere", "cadence": "6h", "org": "chronosphere"},
  {"kind": "greenhouse", "name": "honeycomb", "cadence": "6h", "org": "honeycomb"},
  {"kind": "greenhouse", "name": "lightstep", "cadence": "6h", "org": "lightstep"},
  {"kind": "greenhouse", "name": "datadraw", "cadence": "6h", "org": "datadraw"},
  {"kind": "greenhouse", "name": "grafana", "cadence": "6h", "org": "grafanalabs"},
  {"kind": "greenhouse", "name": "influxdata", "cadence": "6h", "org": "influxdata"},
  {"kind": "greenhouse", "name": "sourcegraph", "cadence": "6h", "org": "sourcegraph"},
  {"kind": "greenhouse", "name": "coder", "cadence": "6h", "org": "coder"},
  {"kind": "greenhouse", "name": "gitpod", "cadence": "6h", "org": "gitpod"},
  {"kind": "greenhouse", "name": "warp", "cadence": "6h", "org": "warp"},
  {"kind": "lever", "name": "canva", "cadence": "6h", "org": "canva"},
  {"kind": "lever", "name": "netflix", "cadence": "6h", "org": "netflix"},
  {"kind": "lever", "name": "spotify", "cadence": "6h", "org": "spotify"},
  {"kind": "lever", "name": "atlassian", "cadence": "6h", "org": "atlassian"},
  {"kind": "lever", "name": "automattic", "cadence": "6h", "org": "automattic"},
  {"kind": "lever", "name": "auth0", "cadence": "6h", "org": "auth0"},
  {"kind": "lever", "name": "algolia", "cadence": "6h", "org": "algolia"},
  {"kind": "lever", "name": "contentful", "cadence": "6h", "org": "contentful"},
  {"kind": "lever", "name": "braze", "cadence": "6h", "org": "braze"},
  {"kind": "lever", "name": "miro", "cadence": "6h", "org": "miro"},
  {"kind": "lever", "name": "hopper", "cadence": "6h", "org": "hopper"},
  {"kind": "lever", "name": "kraken", "cadence": "6h", "org": "kraken"},
  {"kind": "greenhouse", "name": "ripple", "cadence": "hourly", "org": "ripple"},
  {"kind": "lever", "name": "ledger", "cadence": "6h", "org": "ledger"},
  {"kind": "greenhouse", "name": "consensys", "cadence": "hourly", "org": "consensys"},
  {"kind": "lever", "name": "chainalysis", "cadence": "6h", "org": "chainalysis"},
  {"kind": "ashby", "name": "alchemy", "cadence": "hourly", "org": "alchemy"},
  {"kind": "ashby", "name": "opensea", "cadence": "hourly", "org": "opensea"},
  {"kind": "ashby", "name": "uniswap", "cadence": "hourly", "org": "uniswap"},
  {"kind": "lever", "name": "polygon", "cadence": "6h", "org": "polygon"},
  {"kind": "lever", "name": "celo", "cadence": "6h", "org": "clabs"},
  {"kind": "lever", "name": "near", "cadence": "6h", "org": "near"},
  {"kind": "lever", "name": "solana", "cadence": "6h", "org": "solanalabs"},
  {"kind": "lever", "name": "aptos", "cadence": "6h", "org": "aptoslabs"},
  {"kind": "lever", "name": "mysten", "cadence": "6h", "org": "mystenlabs"},
  {"kind": "lever", "name": "matter-labs", "cadence": "6h", "org": "matterlabs"},
  {"kind": "lever", "name": "offchain-labs", "cadence": "6h", "org": "offchainlabs"},
  {"kind": "lever", "name": "optimism", "cadence": "6h", "org": "optimism"},
  {"kind": "lever", "name": "starkware", "cadence": "6h", "org": "starkware"},
  {"kind": "lever", "name": "scroll", "cadence": "6h", "org": "scroll"},
  {"kind": "lever", "name": "monad", "cadence": "6h", "org": "monad"},
  {"kind": "lever", "name": "berachain", "cadence": "6h", "org": "berachain"},
  {"kind": "lever", "name": "movement", "cadence": "6h", "org": "movementlabs"},
  {"kind": "lever", "name": "paradigm", "cadence": "6h", "org": "paradigm"},
  {"kind": "lever", "name": "jump-trading", "cadence": "6h", "org": "jump-trading"},
  {"kind": "lever", "name": "wintermute", "cadence": "6h", "org": "wintermute"},
  {"kind": "lever", "name": "jane-street", "cadence": "6h", "org": "janestreet"},
  {"kind": "lever", "name": "two-sigma", "cadence": "6h", "org": "twosigma"},
  {"kind": "lever", "name": "citadel", "cadence": "6h", "org": "citadel"},
  {"kind": "lever", "name": "hudson-river", "cadence": "6h", "org": "hudson-river-trading"},
  {"kind": "lever", "name": "tower-research", "cadence": "6h", "org": "tower-research-capital"},
  {"kind": "lever", "name": "optiver", "cadence": "6h", "org": "optiver"},
  {"kind": "lever", "name": "flow-traders", "cadence": "6h", "org": "flow-traders"},
  {"kind": "lever", "name": "drw", "cadence": "6h", "org": "drw"},
  {"kind": "lever", "name": "five-rings", "cadence": "6h", "org": "fiverings"},
  {"kind": "lever", "name": "point72", "cadence": "6h", "org": "point72"},
  {"kind": "lever", "name": "millennium", "cadence": "6h", "org": "millennium"},
  {"kind": "lever", "name": "aquatic", "cadence": "6h", "org": "aquatic"},
  {"kind": "lever", "name": "belvedere", "cadence": "6h", "org": "belvedere"},
  {"kind": "lever", "name": "headlands", "cadence": "6h", "org": "headlandstech"},
  {"kind": "ashby", "name": "linear", "cadence": "6h", "org": "linear"},
  {"kind": "ashby", "name": "retool", "cadence": "6h", "org": "retool"},
  {"kind": "ashby", "name": "supabase", "cadence": "6h", "org": "supabase"},
  {"kind": "ashby", "name": "vercel", "cadence": "6h", "org": "vercel"},
  {"kind": "ashby", "name": "posthog", "cadence": "6h", "org": "posthog"},
  {"kind": "ashby", "name": "resend", "cadence": "6h", "org": "resend"},
  {"kind": "ashby", "name": "clerk", "cadence": "6h", "org": "clerk"},
  {"kind": "ashby", "name": "calcom", "cadence": "6h", "org": "cal"},
  {"kind": "ashby", "name": "dub", "cadence": "6h", "org": "dub"},
  {"kind": "ashby", "name": "midjourney", "cadence": "6h", "org": "midjourney"},
  {"kind": "ashby", "name": "elevenlabs", "cadence": "6h", "org": "elevenlabs"},
  {"kind": "ashby", "name": "pika", "cadence": "6h", "org": "pika"},
  {"kind": "ashby", "name": "luma", "cadence": "6h", "org": "luma"},
  {"kind": "ashby", "name": "sunno", "cadence": "6h", "org": "suno"},
  {"kind": "ashby", "name": "cursor-ai", "cadence": "6h", "org": "cursor"},
  {"kind": "ashby", "name": "augment", "cadence": "6h", "org": "augment"},
  {"kind": "ashby", "name": "cognition", "cadence": "6h", "org": "cognition"},
  {"kind": "ashby", "name": "factory", "cadence": "6h", "org": "factory"},
  {"kind": "ashby", "name": "magic-ai", "cadence": "6h", "org": "magic"},
  {"kind": "ashby", "name": "poolside", "cadence": "6h", "org": "poolside"},
  {"kind": "ashby", "name": "hume", "cadence": "6h", "org": "hume"},
  {"kind": "ashby", "name": "braintrust", "cadence": "6h", "org": "braintrust"},
  {"kind": "ashby", "name": "langchain", "cadence": "6h", "org": "langchain"},
  {"kind": "ashby", "name": "llamaindex", "cadence": "6h", "org": "llamaindex"},
  {"kind": "ashby", "name": "unstructured", "cadence": "6h", "org": "unstructured"},
  {"kind": "ashby", "name": "deepgram", "cadence": "6h", "org": "deepgram"},
  {"kind": "ashby", "name": "assemblyai", "cadence": "6h", "org": "assemblyai"},
  {"kind": "ashby", "name": "replicate", "cadence": "6h", "org": "replicate"},
  {"kind": "ashby", "name": "fal-ai", "cadence": "6h", "org": "fal"},
  {"kind": "ashby", "name": "baseten", "cadence": "6h", "org": "baseten"},
  {"kind": "ashby", "name": "cerebras", "cadence": "6h", "org": "cerebras"},
  {"kind": "ashby", "name": "groq", "cadence": "6h", "org": "groq"},
  {"kind": "ashby", "name": "sambanova", "cadence": "6h", "org": "sambanova"},
  {"kind": "ashby", "name": "d-matrix", "cadence": "6h", "org": "dmatrix"},
  {"kind": "ashby", "name": "tenstorrent", "cadence": "6h", "org": "tenstorrent"},
  {"kind": "ashby", "name": "untether-ai", "cadence": "6h", "org": "untetherai"},
  {"kind": "ashby", "name": "lightmatter", "cadence": "6h", "org": "lightmatter"},
  {"kind": "ashby", "name": "etched", "cadence": "6h", "org": "etched"},
  {"kind": "ashby", "name": "matx", "cadence": "6h", "org": "matx"},
  {"kind": "ashby", "name": "rain-ai", "cadence": "6h", "org": "rain"},
  {"kind": "smartrecruiters", "name": "visa", "cadence": "6h", "org": "Visa"},
  {"kind": "smartrecruiters", "name": "linkedin-sr", "cadence": "6h", "org": "LinkedIn"},
  {"kind": "smartrecruiters", "name": "twitter-sr", "cadence": "6h", "org": "Twitter"},
  {"kind": "smartrecruiters", "name": "square-sr", "cadence": "6h", "org": "Block"},
  {"kind": "smartrecruiters", "name": "ubisoft", "cadence": "6h", "org": "Ubisoft2"},
  {"kind": "smartrecruiters", "name": "epic-games", "cadence": "6h", "org": "EpicGames"},
  {"kind": "smartrecruiters", "name": "blizzard", "cadence": "6h", "org": "BlizzardEntertainment"},
  {"kind": "smartrecruiters", "name": "riot-games", "cadence": "6h", "org": "RiotGames"},
  {"kind": "smartrecruiters", "name": "unity", "cadence": "6h", "org": "UnityTechnologies"},
  {"kind": "smartrecruiters", "name": "unreal", "cadence": "6h", "org": "EpicGamesEnterprises"},
  {"kind": "smartrecruiters", "name": "valve", "cadence": "6h", "org": "ValveCorporation"},
  {"kind": "smartrecruiters", "name": "roblox-sr", "cadence": "6h", "org": "Roblox"},
  {"kind": "smartrecruiters", "name": "discord-sr", "cadence": "6h", "org": "Discord"},
  {"kind": "smartrecruiters", "name": "slack-sr", "cadence": "6h", "org": "Slack"},
  {"kind": "smartrecruiters", "name": "stripe-sr", "cadence": "6h", "org": "StripeGlobal"},
  {"kind": "rss", "name": "remoteok", "cadence": "hourly", "url": "https://remoteok.com/api"},
  {"kind": "rss", "name": "arbeitnow", "cadence": "hourly", "url": "https://www.arbeitnow.com/api/job-board-api"},
  {"kind": "rss", "name": "jobicy", "cadence": "hourly", "url": "https://jobicy.com/api/v2/remote-jobs?count=50&geo=usa&industry=dev"},
  {"kind": "rss", "name": "remotive", "cadence": "hourly", "url": "https://remotive.com/api/remote-jobs?category=software-dev&limit=50"},
  {"kind": "rss", "name": "weworkremotely", "cadence": "hourly", "url": "https://weworkremotely.com/categories/remote-programming-jobs.json"},
  {"kind": "rss", "name": "cryptocurrencyjobs", "cadence": "6h", "url": "https://cryptocurrencyjobs.co/index.xml"},
  {"kind": "greenhouse", "name": "Chainlink Labs Careers", "cadence": "6h", "org": "chainlink"},
  {"kind": "rss", "name": "workingnomads", "cadence": "6h", "url": "https://www.workingnomads.com/jobs/export"},
  {"kind": "rss", "name": "jobspresso", "cadence": "6h", "url": "https://jobspresso.co/jobs/feed/"},
  {"kind": "rss", "name": "Remotive", "cadence": "6h", "url": "https://remotive.com/api/remote-jobs"},
  {"kind": "rss", "name": "swissdevjobs", "cadence": "6h", "url": "https://swissdevjobs.ch/api/jobsLight"},
  {"kind": "rss", "name": "cryptojobslist-feed", "cadence": "6h", "url": "https://api.cryptojobslist.com/jobs.rss"},
  {"kind": "rss", "name": "bitcoinjobs-feed", "cadence": "6h", "url": "https://bitbo.io/jobs/feed.xml"},
  {"kind": "rss", "name": "crypto-jobs-feed", "cadence": "6h", "url": "https://crypto.jobs/feed/rss"},
  {"kind": "rss", "name": "remote3-feed", "cadence": "6h", "url": "https://remote3.co/api/rss"},
  {"kind": "rss", "name": "weworkremotely-feed", "cadence": "6h", "url": "https://weworkremotely.com/remote-jobs.rss"},
  {"kind": "rss", "name": "tokyodev-feed", "cadence": "6h", "url": "https://www.tokyodev.com/atom.xml"},
  {"kind": "rss", "name": "jobspresso-feed", "cadence": "6h", "url": "https://jobspresso.co/jobs/feed/"},
  {"kind": "greenhouse", "name": "coinbase-board", "cadence": "hourly", "org": "coinbase"},
  {"kind": "greenhouse", "name": "ripple-board", "cadence": "hourly", "org": "ripple"},
  {"kind": "ashby", "name": "uniswap-board", "cadence": "hourly", "org": "uniswap"},
  {"kind": "ashby", "name": "opensea-board", "cadence": "hourly", "org": "opensea"},
  {"kind": "ashby", "name": "alchemy-board", "cadence": "hourly", "org": "alchemy"},
  {"kind": "greenhouse", "name": "consensys-board", "cadence": "hourly", "org": "consensys"},
  {"kind": "ashby", "name": "stellar-board", "cadence": "hourly", "org": "stellar"},
  {"kind": "ashby-index", "name": "solana-ecosystem-index", "cadence": "6h", "url": "https://jobs.solana.com/", "maxOrgs": 8},
  {"kind": "teamtailor", "name": "teamtailor-career", "cadence": "6h", "url": "https://career.teamtailor.com"},
  {"kind": "teamtailor", "name": "teamtailor-softwarefinder-na", "cadence": "6h", "url": "https://softwarefinder.na.teamtailor.com"},
  {"kind": "recruitee", "name": "recruitee-make", "cadence": "6h", "url": "https://make.recruitee.com"},
  {"kind": "recruitee", "name": "recruitee-happeo", "cadence": "6h", "url": "https://happeo.recruitee.com"},
  {"kind": "recruitee", "name": "recruitee-radix", "cadence": "6h", "url": "https://radix.recruitee.com"},
  {"kind": "personio", "name": "personio-vivid", "cadence": "6h", "url": "https://vivid.jobs.personio.de"},
  {"kind": "greenhouse", "name": "acquia", "cadence": "6h", "org": "acquia"},
  {"kind": "greenhouse", "name": "alphasights", "cadence": "6h", "org": "alphasights"},
  {"kind": "ashby", "name": "andela", "cadence": "6h", "org": "andela"},
  {"kind": "greenhouse", "name": "ark", "cadence": "6h", "org": "ark"},
  {"kind": "lever", "name": "articulate", "cadence": "6h", "org": "articulate"},
  {"kind": "lever", "name": "britecore", "cadence": "6h", "org": "britecore"},
  {"kind": "ashby", "name": "buffer", "cadence": "6h", "org": "buffer"},
  {"kind": "ashby", "name": "calibre", "cadence": "6h", "org": "calibre"},
  {"kind": "ashby", "name": "capchase", "cadence": "6h", "org": "capchase"},
  {"kind": "ashby", "name": "caremessage", "cadence": "6h", "org": "caremessage"},
  {"kind": "ashby", "name": "close", "cadence": "6h", "org": "close"},
  {"kind": "greenhouse", "name": "coalition", "cadence": "6h", "org": "coalition"},
  {"kind": "lever", "name": "collabora", "cadence": "6h", "org": "collabora"},
  {"kind": "greenhouse", "name": "customerio", "cadence": "6h", "org": "customerio"},
  {"kind": "greenhouse", "name": "dashlane", "cadence": "6h", "org": "dashlane"},
  {"kind": "greenhouse", "name": "datacamp", "cadence": "6h", "org": "datacamp"},
  {"kind": "greenhouse", "name": "fastly", "cadence": "6h", "org": "fastly"},
  {"kind": "greenhouse", "name": "godaddy", "cadence": "6h", "org": "godaddy"},
  {"kind": "greenhouse", "name": "gohiring", "cadence": "6h", "org": "gohiring"},
  {"kind": "greenhouse", "name": "intercom", "cadence": "6h", "org": "intercom"},
  {"kind": "lever", "name": "kinsta", "cadence": "6h", "org": "kinsta"},
  {"kind": "greenhouse", "name": "labelbox", "cadence": "6h", "org": "labelbox"},
  {"kind": "ashby", "name": "lightspeed", "cadence": "6h", "org": "lightspeed"},
  {"kind": "ashby", "name": "litmus", "cadence": "6h", "org": "litmus"},
  {"kind": "greenhouse", "name": "liveperson", "cadence": "6h", "org": "liveperson"},
  {"kind": "ashby", "name": "testgorilla", "cadence": "6h", "org": "testgorilla"},
  {"kind": "ashby", "name": "zapier", "cadence": "6h", "org": "zapier"},
  {"kind": "greenhouse", "name": "platformsh", "cadence": "6h", "org": "platformsh"},
  {"kind": "greenhouse", "name": "securityscorecard", "cadence": "6h", "org": "securityscorecard"},
  {"kind": "greenhouse", "name": "metalab", "cadence": "6h", "org": "metalab"},
  {"kind": "greenhouse", "name": "okta", "cadence": "6h", "org": "okta"},
  {"kind": "lever", "name": "renofi", "cadence": "6h", "org": "renofi"},
  {"kind": "greenhouse", "name": "scandit", "cadence": "6h", "org": "scandit"},
  {"kind": "greenhouse", "name": "streamnative", "cadence": "6h", "org": "streamnative"},
  {"kind": "greenhouse", "name": "turing", "cadence": "6h", "org": "turing"},
  {"kind": "ashby", "name": "quora", "cadence": "6h", "org": "quora"},
  {"kind": "greenhouse", "name": "rocketchat", "cadence": "6h", "org": "rocketchat"},
  {"kind": "greenhouse", "name": "twilio", "cadence": "6h", "org": "twilio"},
  {"kind": "lever", "name": "mindful", "cadence": "6h", "org": "mindful"},
  {"kind": "ashby", "name": "mux", "cadence": "6h", "org": "mux"},
  {"kind": "ashby", "name": "percona", "cadence": "6h", "org": "percona"},
  {"kind": "ashby", "name": "primer", "cadence": "6h", "org": "primer"},
  {"kind": "ashby", "name": "recharge", "cadence": "6h", "org": "recharge"},
  {"kind": "greenhouse", "name": "udacity", "cadence": "6h", "org": "udacity"},
  {"kind": "greenhouse", "name": "wizeline", "cadence": "6h", "org": "wizeline"},
  {"kind": "greenhouse", "name": "mixmax", "cadence": "6h", "org": "mixmax"},
  {"kind": "greenhouse", "name": "openzeppelin", "cadence": "6h", "org": "openzeppelin"},
];

export interface PythonOnlySource {
  name: string;
  adapter: string;
  url: string;
}

// Cannot run on Workers (TLS impersonation / RSA / browser). Stays on Python/Actions.
export const PYTHON_ONLY_SOURCES: PythonOnlySource[] = [
  {"name": "bayt-egypt-tech", "adapter": "bayt", "url": "https://www.bayt.com/en/egypt/jobs/"},
  {"name": "naukri-india-remote", "adapter": "naukri", "url": "https://www.naukri.com/"},
  {"name": "Calyptus", "adapter": "web", "url": "https://calyptus.co/"},
  {"name": "Degen Crypto Jobs", "adapter": "web", "url": "https://degencryptojobs.com/"},
  {"name": "CryptoJobs.com", "adapter": "web", "url": "https://cryptojobs.com/"},
  {"name": "Solana Ecosystem Jobs", "adapter": "web", "url": "https://jobs.solana.com/"},
  {"name": "Web3internships", "adapter": "web", "url": "https://www.web3internships.com/"},
  {"name": "Ton Jobs", "adapter": "web", "url": "https://jobs.ton.org/jobs"},
  {"name": "Web3.career", "adapter": "web", "url": "https://web3.career/"},
  {"name": "CryptoJobsList", "adapter": "web", "url": "https://cryptojobslist.com/"},
  {"name": "Blockchain Works", "adapter": "web", "url": "https://blockchain.works-hub.com/"},
  {"name": "Ethereum Jobs", "adapter": "web", "url": "https://ethgigs.com/"},
  {"name": "DeFi Jobs", "adapter": "web", "url": "https://defi.jobs/"},
  {"name": "BitcoinJobs", "adapter": "web", "url": "https://bitcoinjobs.com/"},
  {"name": "CryptoJobs", "adapter": "web", "url": "https://crypto.jobs/"},
  {"name": "Remote3", "adapter": "web", "url": "https://remote3.co/"},
  {"name": "Web3 Army", "adapter": "web", "url": "https://web3army.xyz/"},
  {"name": "useWeb3 Jobs", "adapter": "web", "url": "https://www.useweb3.xyz/jobs"},
  {"name": "Crypto Recruit", "adapter": "web", "url": "https://cryptorecruit.com/"},
  {"name": "Blockchain Job Board", "adapter": "web", "url": "https://blockchainjobboard.com/"},
  {"name": "CryptoJobsDB", "adapter": "web", "url": "https://cryptojobsdb.com/"},
  {"name": "CryptoJobLand", "adapter": "web", "url": "https://cryptojob.land/"},
  {"name": "Web3 Jobs", "adapter": "web", "url": "https://web3jobs.ai/"},
  {"name": "Binance Careers", "adapter": "web", "url": "https://www.binance.com/en/careers"},
  {"name": "CryptoJobsDaily", "adapter": "web", "url": "https://cryptojobsdaily.com/"},
  {"name": "NFT Jobs", "adapter": "web", "url": "https://nftjobs.com/"},
  {"name": "Crypto Careers", "adapter": "web", "url": "https://crypto-careers.com/"},
  {"name": "CryptoJobSearch", "adapter": "web", "url": "https://cryptojobsearch.com/"},
  {"name": "Web3 Talent", "adapter": "web", "url": "https://web3talent.com/"},
  {"name": "Blocktribe", "adapter": "web", "url": "https://blocktribe.com/"},
  {"name": "Blockchain Developers", "adapter": "web", "url": "https://blockchaindevelopers.io/"},
  {"name": "Solidity Jobs", "adapter": "web", "url": "https://solidityjobs.com/"},
  {"name": "SmartContractJobs", "adapter": "web", "url": "https://smartcontractjobs.com/"},
  {"name": "Aave Careers", "adapter": "web", "url": "https://aave.com/careers/"},
  {"name": "CryptoJobHunt", "adapter": "web", "url": "https://cryptojobhunt.com/"},
  {"name": "Stellar Jobs", "adapter": "web", "url": "https://www.stellar.org/careers"},
  {"name": "PompCryptoJobs", "adapter": "web", "url": "https://pompcryptojobs.com/"},
  {"name": "Remote \ud83d\udc8e Web3 Jobs", "adapter": "web", "url": "https://web3.career/remote-jobs"},
  {"name": "Arc (formerly Vettery)", "adapter": "web", "url": "https://arc.dev/"},
  {"name": "AngelList Talent", "adapter": "web", "url": "https://angel.co/talent"},
  {"name": "Wellfound (formerly AngelList)", "adapter": "web", "url": "https://wellfound.com/"},
  {"name": "Toptal", "adapter": "web", "url": "https://www.toptal.com/"},
  {"name": "Hired", "adapter": "web", "url": "https://hired.com/"},
  {"name": "Gun.io", "adapter": "web", "url": "https://www.gun.io/"},
  {"name": "YCombinator Jobs", "adapter": "web", "url": "https://www.workatastartup.com/"},
  {"name": "FlexJobs", "adapter": "web", "url": "https://www.flexjobs.com/"},
  {"name": "PowerToFly", "adapter": "web", "url": "https://powertofly.com/"},
  {"name": "Remote.co", "adapter": "web", "url": "https://remote.co/"},
  {"name": "JustRemote", "adapter": "web", "url": "https://justremote.co/"},
  {"name": "DailyRemote", "adapter": "web", "url": "https://dailyremote.com/"},
  {"name": "RemoteLeaf", "adapter": "web", "url": "https://remoteleaf.com/"},
  {"name": "RemoteMore", "adapter": "web", "url": "https://remotemore.com/"},
  {"name": "Vanhack", "adapter": "web", "url": "https://vanhack.com/"},
  {"name": "Talent.io", "adapter": "web", "url": "https://www.talent.io/"},
  {"name": "NodeFlair", "adapter": "web", "url": "https://nodeflair.com/"},
  {"name": "Stack Overflow Jobs", "adapter": "web", "url": "https://stackoverflow.com/jobs"},
  {"name": "Indeed", "adapter": "web", "url": "https://www.indeed.com/"},
  {"name": "Glassdoor", "adapter": "web", "url": "https://www.glassdoor.com/"},
  {"name": "Dice", "adapter": "web", "url": "https://www.dice.com/"},
  {"name": "HackerRank Jobs", "adapter": "web", "url": "https://www.hackerrank.com/jobs"},
  {"name": "Gitcoin", "adapter": "web", "url": "https://gitcoin.co/"},
  {"name": "DAO Jobs", "adapter": "web", "url": "https://daojobs.io/"},
  {"name": "https://ethglobal.com/auth?useredirect=/jobs", "adapter": "web", "url": "https://ethglobal.com/auth?use_redirect=/jobs"},
  {"name": "WUZZUF", "adapter": "web", "url": "https://wuzzuf.net/"},
  {"name": "Bayt", "adapter": "web", "url": "https://www.bayt.com/"},
  {"name": "GulfTalent", "adapter": "web", "url": "https://www.gulftalent.com/"},
  {"name": "Jobbatical", "adapter": "web", "url": "https://jobbatical.com/"},
  {"name": "Eurojobs", "adapter": "web", "url": "https://www.eurojobs.com/"},
  {"name": "JobsDB", "adapter": "web", "url": "https://www.jobsdb.com/"},
  {"name": "TokyoDev", "adapter": "web", "url": "https://www.tokyodev.com/"},
  {"name": "JobStreet", "adapter": "web", "url": "https://www.jobstreet.com/"},
  {"name": "https://www.jobberman.com/jobs?q=blockchain", "adapter": "web", "url": "https://www.jobberman.com/jobs?q=blockchain"},
  {"name": "Polygon Ecosystem Jobs", "adapter": "web", "url": "https://jobs.polygon.technology/"},
  {"name": "Chainlink Labs Careers", "adapter": "web", "url": "https://chainlinklabs.com/careers"},
  {"name": "ConsenSys Careers", "adapter": "web", "url": "https://consensys.net/careers/"},
  {"name": "Coinbase Careers", "adapter": "web", "url": "https://www.coinbase.com/careers"},
  {"name": "Ripple Careers", "adapter": "web", "url": "https://ripple.com/careers/"},
  {"name": "Polygon Careers", "adapter": "web", "url": "https://polygon.technology/careers/"},
  {"name": "Alchemy Jobs", "adapter": "web", "url": "https://www.alchemy.com/jobs"},
  {"name": "OpenSea Careers", "adapter": "web", "url": "https://opensea.io/careers"},
  {"name": "Uniswap Careers", "adapter": "web", "url": "https://uniswap.org/careers"},
  {"name": "RemoteOK", "adapter": "web", "url": "https://remoteok.com/"},
  {"name": "Remotive", "adapter": "web", "url": "https://remotive.com/"},
  {"name": "web3-career-jsonld", "adapter": "web", "url": "https://web3.career/"},
];
